language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - chartgerink/osfr

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  - bash <(curl -s https://codecov.io/bash)
