language: r
os: linux
cache: packages

script:
- R CMD build . --no-build-vignettes
- travis_wait 20 R CMD check *tar.gz --ignore-vignettes --no-tests

jobs:
  include:
  - r: oldrel
  - r: devel
  - r: release
    # after_success:
    # - Rscript -e 'covr::codecov()'
    after_failure:
    - cat osfr.log
    before_deploy:
    - Rscript -e 'dir(recursive = TRUE)' && Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      on:
        branch: fix-pkgdown
      provider: script
      script: Rscript -e 'dir(recursive = TRUE)' && Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
